### ISSUE TITLE
Coupons don't seem to clip anymore

### ISSUE THREAD

**Issue by jdclark73** [kton/Safeway-Just-for-u#1]
Safeway seems to have changed something. This was working last week but when I tried today, it doesn't seem to be working. I'm not sure if it's adding the coupons, but not changing the tally, or if it's not adding at all. I don't even get the alert pop up saying that it's adding a certain number of coupons.

**Comment by kton** [comment]
Thanks for the heads up.
I don't actually shop at Safeway much and/or use this on a regular basis.

Looks like session cookies are no longer used for authentication when clipping the coupons.
The script is no longer adding coupons as a result.

Access/refresh tokens via Okta seem to be partially implemented, but the changes don't seem to be final yet (site maintenance at 10PM Pacific).

Seems to be an easy fix.
Going to wait a week or so for the dust to settle before pushing out a new version.

**Comment by jdclark73** [comment]
Thanks. I appreciate you working on this, especially since I might be one of the very few (only?) people using it

**Comment by q00u** [comment]
I use it, my mom uses it, I tell everyone about it... This is the last working one.

**Comment by jdclark73** [comment]
Just tested the new version, and it seems to be working. Thanks!

**Comment by a9013** [comment]
Hi, please update, Safeway updated their website.

**Comment by kton** [comment]
Updated. New default branch - only tested on Chrome.

**Comment by a9013** [comment]
Works on Firefox. Thank you! 👍

**Comment by cadroidman** [comment]
Hey there - how can I make a donation to you for this? It helps me save a ton of time and money.

**Comment by jwgooru** [comment]
Thx you so march for doing this! Want to let you know many people are using your script. Same as comment above, it helps us save so much time and money. :)
https://slickdeals.net/f/5728664-safeway-just4u-automatically-add-coupons-to-your-account?v=1&page=9

**Comment by kton** [comment]
Thank you all for the positive feedback.

I appreciate the gesture but will not be accepting donations - instead, please consider making a charitable contribution.

If you want to be rewarded for your generosity in the same way I do... then I suggest going to Humble Bundle:
1. choose a compelling bundle offer from the front page at https://www.humblebundle.com/
a. (optional) on a bundle page - find the part where it says 'SUPPORT CHARITY'
b. (optional) choose a specific charity where it says 'If you would like to support a different charity, ___select a new one___ from our database of thousands'
2. at the bottom (payment form) - find the part where it says 'Choose where your money goes', expand it, and pump that Charity slider

If you still want to thank me in some way for maintaining this script, I dropped a bunch of referral links at:

https://gist.github.com/kton/f34560924f51b323c284d28dc8e7b7d0

Please do your own research w/r/t what each service, site, or product provides (ranked in money-saving usefulness - top to bottom).

Chances are that if you're reading this and have a Slickdeals account, you already have an account at most of those and are ineligible for a referral.

Worth a shot though. :)
